### ISSUE TITLE
Include support for local llms (e.g., Ollama)

### ISSUE THREAD

**Issue by arsaboo** [databonsai/databonsai#1]
Given that most models follow the same endpoints, it would be great to add support of local LLM providers like Ollama.

**Comment by arsaboo** [comment]
I saw Ollama in the list of providers, but I did not see it in the docs.

**Comment by alvin-r** [comment]
I just added it in yesterday! docs/OllamaProvider.md 
Feel free to try it out. Smaller models don't work well for batch methods however, it doesn't seem to be good enough at instruction following (gpt-4 and claude works best for these) But everything else works as expected!

**Comment by arsaboo** [comment]
I just tested out with Llama3, and it worked well for me:

```bash
Categorizing: 100%|██████████| 10/10 [00:01<00:00,  7.66row/s]
0        Weather
1         Sports
2    Celebrities
3       Politics
4         Others
5        Weather
6         Sports
7    Celebrities
8       Politics
9         Others
```

What did you test it on? Any other dataset to test this thing on?

**Comment by alvin-r** [comment]
Categorization is a straightforward task, but for multicategorization, or perhaps more complex tasks, it'll not do as well for larger batches. Let me know how it goes for you when you try it with other datasets! I haven't tested open source models too extensively yet
